name: insta_clone
description: Instagram clone built with Flutter and Firebase
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (versiones compatibles)
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  
  # Utilities
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  uuid: ^4.5.1
  
  # Adicionales para UI
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/